package graphql

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"

	"gerp/internal/eam"
	"gerp/internal/mdm"
	"gerp/internal/pipeline"
	"gerp/internal/revenue"
	"gerp/internal/scm"
)

// This file implements the graph mappings requested by the schema.

type Resolver struct {
	MDMService      mdm.Service
	EAMService      eam.Service
	RevenueService  revenue.Service
	TemporalTrigger func(ctx context.Context, req pipeline.FulfillmentRequest) error
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type salesOrderResolver struct{ *Resolver }
type inventoryLotResolver struct{ *Resolver }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SalesOrder returns SalesOrderResolver implementation.
func (r *Resolver) SalesOrder() SalesOrderResolver { return &salesOrderResolver{r} }

// InventoryLot returns InventoryLotResolver implementation.
func (r *Resolver) InventoryLot() InventoryLotResolver { return &inventoryLotResolver{r} }

// =========================================================================
// MUTATIONS
// =========================================================================

// CreateSalesOrder natively invokes the Temporal Saga execution boundary.
func (r *mutationResolver) CreateSalesOrder(ctx context.Context, input CreateOrderInput) (*revenue.SalesOrder, error) {
	// Structure the payload for the Pipeline Nervous System
	var pipelineItems []pipeline.OrderItem
	for _, item := range input.Items {
		pipelineItems = append(pipelineItems, pipeline.OrderItem{
			LotID:    item.LotID,
			Quantity: item.Quantity,
		})
	}

	req := pipeline.FulfillmentRequest{
		TransactionID:    input.TransactionID,
		CustomerID:       input.CustomerID,
		AccountDebitID:   input.AccountDebitID,
		AccountCreditID:  input.AccountCreditID,
		TotalAmountCents: int64(input.TotalAmountCents),
		Items:            pipelineItems,
	}

	// Asynchronously trigger the Saga via the pipeline
	if err := r.TemporalTrigger(ctx, req); err != nil {
		return nil, fmt.Errorf("failed to invoke saga orchestration: %w", err)
	}

	// Logically persist the initial domain truth before saga concludes async
	order := &revenue.SalesOrder{
		ID:         input.TransactionID,
		CustomerID: input.CustomerID,
		TotalValue: int64(input.TotalAmountCents),
		Status:     "PENDING_SAGA_COMPLETION",
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
	}

	if err := r.RevenueService.InsertSalesOrder(ctx, order); err != nil {
		return nil, err
	}

	return order, nil
}

// =========================================================================
// QUERIES
// =========================================================================

func (r *queryResolver) GetSalesOrder(ctx context.Context, id uuid.UUID) (*revenue.SalesOrder, error) {
	return r.RevenueService.GetSalesOrder(ctx, id)
}

func (r *queryResolver) GetInventoryLot(ctx context.Context, id uuid.UUID) (*scm.InventoryLot, error) {
	// Dummy query resolution (Assumes SCM service exposes GetLot inherently)
	return nil, nil
}

// =========================================================================
// GRAPH STITCHING / GOLDEN THREAD RESOLVERS
// =========================================================================

// Customer crosses from Revenue over to MDM utilizing the CustomerID pointer.
func (r *salesOrderResolver) Customer(ctx context.Context, obj *revenue.SalesOrder) (*mdm.GlobalEntity, error) {
	// Resolves the Golden Record via the internal isolated domain logic
	entity, _, err := r.MDMService.GetGlobalEntityWithMappings(ctx, obj.CustomerID)
	return entity, err
}

// Warehouse deeply bridges SCM hardware components to EAM physical architecture.
func (r *inventoryLotResolver) Warehouse(ctx context.Context, obj *scm.InventoryLot) (*eam.Asset, error) {
	// Resolves the Physical Asset layout independently
	asset, _, err := r.EAMService.GetAssetWithLogs(ctx, obj.WarehouseID)
	return asset, err
}

// =========================================================================
// GENERATED TYPE STUBS (Normally handled generated by gqlgen)
// =========================================================================

type MutationResolver interface {
	CreateSalesOrder(ctx context.Context, input CreateOrderInput) (*revenue.SalesOrder, error)
}
type QueryResolver interface {
	GetSalesOrder(ctx context.Context, id uuid.UUID) (*revenue.SalesOrder, error)
	GetInventoryLot(ctx context.Context, id uuid.UUID) (*scm.InventoryLot, error)
}
type SalesOrderResolver interface {
	Customer(ctx context.Context, obj *revenue.SalesOrder) (*mdm.GlobalEntity, error)
}
type InventoryLotResolver interface {
	Warehouse(ctx context.Context, obj *scm.InventoryLot) (*eam.Asset, error)
}
type CreateOrderInput struct {
	TransactionID    uuid.UUID        `json:"transactionId"`
	CustomerID       uuid.UUID        `json:"customerId"`
	AccountDebitID   uuid.UUID        `json:"accountDebitId"`
	AccountCreditID  uuid.UUID        `json:"accountCreditId"`
	TotalAmountCents int              `json:"totalAmountCents"`
	Items            []OrderItemInput `json:"items"`
}
type OrderItemInput struct {
	LotID    uuid.UUID `json:"lotId"`
	Quantity int       `json:"quantity"`
}

type Config struct{ Resolvers *Resolver }
func NewExecutableSchema(c Config) *executableSchema { return &executableSchema{} }
type executableSchema struct{}
func (e *executableSchema) Exec(ctx context.Context) {}
